### ISSUE TITLE
Any plans on supporting React 18?

### ISSUE THREAD

**Issue by junzhengca** [K-Sato1995/react-toc#109]
Currently the peer dependencies are listed as React 15 and 16 only. Any plans on supporting React 18? Looks like a great library, really want to use in one of my personal projects.

**Comment by K-Sato1995** [comment]
@junzhengca 

Thanks for creating an issue here:)!
Haven't had much time to work on my personal projects lately. But I will definitely look into this soon!

**Comment by K-Sato1995** [comment]
@junzhengca 
Should work with React(>=16) without any warning from [v3.1.0](https://www.npmjs.com/package/react-toc)!!
 

Thanks!


-[https://github.com/K-Sato1995/react-toc/releases/tag/v3.1.0
