### ISSUE TITLE
Update react and react-dom peer deps to include ^17.0.0 and ^18.0.0

### ISSUE THREAD

**Issue by dnlbaldwin** [K-Sato1995/react-toc#66]
Hi, would you be able to bump the peerDependencies in your package.json to allow for react and react-dom 17 and 18?

**Comment by K-Sato1995** [comment]
@dnlbaldwin 

HI! Yes, I'd definitely look into that when I have time!

**Comment by K-Sato1995** [comment]
@dnlbaldwin 

Updated the package!!
It should work with React/react-dom V17 or V18 without any problem now!

Thanks for commenting here👍👍

https://github.com/K-Sato1995/react-toc/releases/tag/v3.0.0
